### PR TITLE
add uni/bidirectional_sequence_rnn && UT

### PR DESCRIPTION
**Pull request by MESeraph**
Issue:
1. The result will be error if UT select Tanh activation. 
2. **bidirectional_sequence_rnn_ext.cc** is written to be compatible with onnx.
In the corresponding UT,  the third row of  **bias_data** cannot be obtained. I checked the code many times, but found no problems.
Please check the above two questions, thank you.

### CODE REVIEW

**Comment by sunshinemyson** [comment]
@MESeraph ,

Thanks for contribute. We will try to merge changes inside "internal" firstly. We will keep you posted.

**Comment by sunshinemyson** [comment]
@MESeraph ,
Could you double-check if "internal" change already updated in V1.1.50 or not?

**Comment by MESeraph** [comment]
@sunshinemyson 
I looked at the changes in internal, and it seems that my changes have not been included.

**Comment by sunshinemyson** [comment]
@MESeraph M，

Yes，it is not there yet. We are going to update internal folder before end of Oct. Then you will have it.

**Pull request closed without merging**
