### PR TITLE
scatter bug

### PR DESCRIPTION
**Pull request by Gideon0805**
There is a bug in ScatterND, while the input size exceeds a specific size.

### CODE REVIEW

**Comment by antkillerfarm** [comment]
144x6x96=82944>65535
index must be less than 16bit.

**Comment by Gideon0805** [comment]
Is the 16bit limit on software or on hardware?
Is there any possibility to extend this limit?

**Comment by antkillerfarm** [comment]
> Is the 16bit limit on software or on hardware? Is there any possibility to extend this limit?

It is a hardware limit. But if your hardware has 40bit addr feature, this limit will extend to 32bit.

**Comment by sunshinemyson** [comment]
This is limitation from HW spec. Won't fix

**Pull request closed without merging**
